### ISSUE TITLE
Scrollbars are messed up

### ISSUE THREAD

**Issue by he3als** [Aetopia/Dark-Mode-Titlebars#1]
When downloading a file in Firefox/LibreWolf, the scrollbar is all broken in the sidebar, and it only fixes its self once you scroll. A potential fix could be having exclusions.

![hi](https://user-images.githubusercontent.com/65787561/208744698-a67feead-d573-4efd-bcea-a6897e7cf7e4.png)

**Comment by he3als** [comment]
Also seems to randomly happen with scrollbars generally.

**Comment by he3als** [comment]
Some scrollbars completely break.

https://user-images.githubusercontent.com/65787561/208764555-1bdd6011-6f42-4aac-aa26-c938365e8fa3.mp4

**Comment by he3als** [comment]
Another example.

![dllhost_Mlq3L1m4le](https://user-images.githubusercontent.com/65787561/208766654-a0bdd323-91fc-40ce-ab3a-47d0c9cbb399.png)

**Comment by Aetopia** [comment]
Blacklist added for problematic applications.
