### ISSUE TITLE
Paint and other programs with a toolbar in the titlebar are broken

### ISSUE THREAD

**Issue by he3als** [Aetopia/Dark-Mode-Titlebars#2]
https://user-images.githubusercontent.com/65787561/208781105-889ef3f5-146e-498d-ac23-944ef94d3544.mp4

**Comment by he3als** [comment]
I would imagine that it also affects Wordpad.

**Comment by Aetopia** [comment]
I need a full list of programs being affected by this.

**Comment by Aetopia** [comment]
New plans:

1. Rewrite in Nim using winim.
2. Add a blacklist feature for applications.

**Comment by Aetopia** [comment]
Blacklist has been added!
